### ISSUE TITLE
[21pt] Research and test techniques for determining pixel counts for each LULC for any given polygon dataset

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [BradfordBates-NOAA/catchment-enricher#7]
Use open-source code.

Return to this on Tuesday to identify requirements/design.

**Comment by sophiecress** [comment]
Do the pandas and geopandas libraries count as open-source?

**Comment by sophiecress** [comment]
Research results for sample pixel count scripts:

1. The Zonal Statistics plugin in QGIS could be a good starting point, since we want raster statistics per polygon, but we'd have to modify the script to separate the statistics by cover class.

- Step-by-step guide and code to this open-source plugin: [https://towardsdatascience.com/zonal-statistics-algorithm-with-python-in-4-steps-382a3b66648a](url)
- Another example code of this from a github user: [https://gist.github.com/perrygeo/5667173](url)
- The plugin code extracted directly from QGIS: [zonalstats-0.0.4.zip](https://github.com/BradfordBates-NOAA/catchment-enricher/files/8056219/zonalstats-0.0.4.zip)

2. It looks like there are several ways to modify the zonal statistics code by raster categories. They use different libraries and the strategies vary in their simplicity. All provide good suggestions!

- Two stack exchange posts with different approaches:
- [https://gis.stackexchange.com/questions/81035/how-to-calculate-custom-zonal-statistics/81047#81047](url)
- [https://gis.stackexchange.com/questions/408583/zonal-histogram-python](url)

- A lesson plan with another idea:
- [https://carpentries-incubator.github.io/geospatial-python/12-zonal-statistics-raster/index.html](url)

- Two other QGIS plugin codes that accomplish this:
- [RasterPixelCountStat-0.2.0.zip](https://github.com/BradfordBates-NOAA/catchment-enricher/files/8056231/RasterPixelCountStat-0.2.0.zip)
- [LecoS-3.0.0.zip](https://github.com/BradfordBates-NOAA/catchment-enricher/files/8056232/LecoS-3.0.0.zip)

**Comment by BradfordBates-NOAA** [comment]
Yes, pandas and geopandas are open source.

**Comment by fastnish** [comment]
I like the towardsdatascience tutorial. I feel we can use an if statement or a for loop to count the pixels for each NLCD class. So it'll end up looking like a table (something like whats below).

<img width="825" alt="Screen Shot 2022-02-15 at 8 36 32 AM" src="https://user-images.githubusercontent.com/55287390/154083647-4e018ab3-b5be-4bb7-b64d-13c16de04c49.png">

**Comment by fastnish** [comment]
@BradfordBates-NOAA Hey Brad! Sophie and I finished up the script. Where would you like us to upload the .py file?

**Comment by BradfordBates-NOAA** [comment]
Nice! Let's go over that process today.
